import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import {
  generateMarkdownReport,
  generateJSONReport,
  generateCSVReport,
  createSummary,
  generateReportFilename,
} from '@/lib/hydration/reporter'
import type { HydrationSummary, HydrationTask } from '@/types/hydration'

describe('reporter', () => {
  const mockTasks: HydrationTask[] = [
    {
      id: 'task-1',
      category: 'groups',
      operation: 'create',
      itemName: 'All Windows Devices',
      status: 'success',
      startTime: new Date('2024-01-15T10:00:00Z'),
      endTime: new Date('2024-01-15T10:00:02Z'),
    },
    {
      id: 'task-2',
      category: 'groups',
      operation: 'create',
      itemName: 'All macOS Devices',
      status: 'success',
      startTime: new Date('2024-01-15T10:00:03Z'),
      endTime: new Date('2024-01-15T10:00:05Z'),
    },
    {
      id: 'task-3',
      category: 'filters',
      operation: 'create',
      itemName: 'Corporate Windows Devices',
      status: 'failed',
      error: 'Insufficient permissions',
      startTime: new Date('2024-01-15T10:00:06Z'),
      endTime: new Date('2024-01-15T10:00:07Z'),
    },
    {
      id: 'task-4',
      category: 'compliance',
      operation: 'create',
      itemName: 'Windows Security Baseline',
      status: 'skipped',
      startTime: new Date('2024-01-15T10:00:08Z'),
      endTime: new Date('2024-01-15T10:00:08Z'),
    },
  ]

  const mockSummary: HydrationSummary = {
    tenantId: '00000000-0000-0000-0000-000000000001',
    operationMode: 'create',
    startTime: new Date('2024-01-15T10:00:00Z'),
    endTime: new Date('2024-01-15T10:10:00Z'),
    duration: 600000, // 10 minutes
    stats: {
      total: 4,
      created: 2,
      deleted: 0,
      skipped: 1,
      failed: 1,
    },
    categoryBreakdown: {
      groups: { total: 2, success: 2, skipped: 0, failed: 0 },
      filters: { total: 1, success: 0, skipped: 0, failed: 1 },
      compliance: { total: 1, success: 0, skipped: 1, failed: 0 },
    },
    errors: [
      {
        task: 'Corporate Windows Devices',
        message: 'Insufficient permissions',
        timestamp: new Date('2024-01-15T10:00:07Z'),
      },
    ],
    warnings: [],
  }

  describe('generateMarkdownReport', () => {
    it('generates valid markdown with all sections', () => {
      const markdown = generateMarkdownReport(mockSummary, mockTasks)

      // Check header
      expect(markdown).toContain('# Intune Hydration Report')
      expect(markdown).toContain('**Tenant ID**: 00000000-0000-0000-0000-000000000001')
      expect(markdown).toContain('**Operation**: Create')
      expect(markdown).toContain('**Duration**: 10m 0s')

      // Check summary section
      expect(markdown).toContain('## Summary')
      expect(markdown).toContain('- **Total Tasks**: 4')
      expect(markdown).toContain('- **Created**: 2')
      expect(markdown).toContain('- **Skipped**: 1')
      expect(markdown).toContain('- **Failed**: 1')

      // Check category breakdown
      expect(markdown).toContain('## Category Breakdown')
      expect(markdown).toContain('### Dynamic Groups (2)')
      expect(markdown).toContain('### Device Filters (1)')
      expect(markdown).toContain('### Compliance Policies (1)')

      // Check task details
      expect(markdown).toContain('## Task Details')
      expect(markdown).toContain('✓ All Windows Devices')
      expect(markdown).toContain('✓ All macOS Devices')
      expect(markdown).toContain('✗ Corporate Windows Devices')
      expect(markdown).toContain('⊗ Windows Security Baseline')

      // Check errors section
      expect(markdown).toContain('## Errors')
      expect(markdown).toContain('Corporate Windows Devices: Insufficient permissions')

      // Check footer
      expect(markdown).toContain('Generated by [Intune Hydration Kit]')
    })

    it('includes task durations', () => {
      const markdown = generateMarkdownReport(mockSummary, mockTasks)
      expect(markdown).toContain('- Duration: 2s')
    })

    it('includes error messages in task details', () => {
      const markdown = generateMarkdownReport(mockSummary, mockTasks)
      expect(markdown).toContain('- Error: Insufficient permissions')
    })

    it('handles delete operation mode', () => {
      const deleteSummary = { ...mockSummary, operationMode: 'delete' as const }
      const markdown = generateMarkdownReport(deleteSummary, mockTasks)
      expect(markdown).toContain('**Operation**: Delete')
    })

    it('handles create operation mode', () => {
      const createSummary = { ...mockSummary, operationMode: 'create' as const }
      const markdown = generateMarkdownReport(createSummary, mockTasks)
      expect(markdown).toContain('**Operation**: Create')
    })

    it('handles empty errors array', () => {
      const noErrorSummary = { ...mockSummary, errors: [] }
      const markdown = generateMarkdownReport(noErrorSummary, mockTasks)
      // Should not contain errors section header followed by error content
      const errorSectionIndex = markdown.indexOf('## Errors')
      // If errors section exists, check what follows
      if (errorSectionIndex !== -1) {
        const afterErrors = markdown.slice(errorSectionIndex + 10, errorSectionIndex + 50)
        expect(afterErrors).toContain('---') // Should go straight to footer
      }
    })

    it('formats duration correctly for different time ranges', () => {
      // Less than a minute
      const shortSummary = { ...mockSummary, duration: 45000 }
      let markdown = generateMarkdownReport(shortSummary, mockTasks)
      expect(markdown).toContain('**Duration**: 45s')

      // Over an hour
      const longSummary = { ...mockSummary, duration: 3725000 } // 1h 2m 5s
      markdown = generateMarkdownReport(longSummary, mockTasks)
      expect(markdown).toContain('**Duration**: 1h 2m 5s')
    })
  })

  describe('generateJSONReport', () => {
    it('generates valid JSON structure', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report).toHaveProperty('summary')
      expect(report).toHaveProperty('tasks')
      expect(report).toHaveProperty('metadata')
    })

    it('includes summary data', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report.summary.tenantId).toBe('00000000-0000-0000-0000-000000000001')
      expect(report.summary.operationMode).toBe('create')
      expect(report.summary.stats.total).toBe(4)
    })

    it('includes all tasks with correct properties', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report.tasks).toHaveLength(4)
      expect(report.tasks[0]).toMatchObject({
        id: 'task-1',
        category: 'groups',
        operation: 'create',
        itemName: 'All Windows Devices',
        status: 'success',
      })
    })

    it('calculates task duration', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report.tasks[0].duration).toBe(2000) // 2 seconds
    })

    it('handles tasks without start/end times', () => {
      const tasksWithoutTimes: HydrationTask[] = [{
        id: 'task-no-time',
        category: 'groups',
        operation: 'create',
        itemName: 'Test Group',
        status: 'pending',
      }]

      const jsonString = generateJSONReport(mockSummary, tasksWithoutTimes)
      const report = JSON.parse(jsonString)

      expect(report.tasks[0].startTime).toBeUndefined()
      expect(report.tasks[0].endTime).toBeUndefined()
      expect(report.tasks[0].duration).toBeNull()
    })

    it('includes metadata with version and timestamp', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report.metadata.reportVersion).toBe('1.0')
      expect(report.metadata.generatedAt).toBeTruthy()
    })

    it('formats dates as ISO strings', () => {
      const jsonString = generateJSONReport(mockSummary, mockTasks)
      const report = JSON.parse(jsonString)

      expect(report.tasks[0].startTime).toBe('2024-01-15T10:00:00.000Z')
      expect(report.tasks[0].endTime).toBe('2024-01-15T10:00:02.000Z')
    })
  })

  describe('generateCSVReport', () => {
    it('generates valid CSV with headers', () => {
      const csv = generateCSVReport(mockTasks)
      const lines = csv.split('\n')

      expect(lines[0]).toBe(
        'Category,Item Name,Operation,Status,Error,Warning,Start Time,End Time,Duration (ms)'
      )
    })

    it('includes all tasks as rows', () => {
      const csv = generateCSVReport(mockTasks)
      const lines = csv.split('\n')

      expect(lines).toHaveLength(5) // 1 header + 4 tasks
    })

    it('escapes quotes in item names', () => {
      const tasksWithQuotes: HydrationTask[] = [{
        id: 'task-quotes',
        category: 'groups',
        operation: 'create',
        itemName: 'Group with "quotes" inside',
        status: 'success',
        startTime: new Date('2024-01-15T10:00:00Z'),
        endTime: new Date('2024-01-15T10:00:01Z'),
      }]

      const csv = generateCSVReport(tasksWithQuotes)
      expect(csv).toContain('"Group with ""quotes"" inside"')
    })

    it('escapes quotes in error messages', () => {
      const tasksWithErrorQuotes: HydrationTask[] = [{
        id: 'task-error-quotes',
        category: 'filters',
        operation: 'create',
        itemName: 'Test Filter',
        status: 'failed',
        error: 'Error: "Something" went wrong',
        startTime: new Date('2024-01-15T10:00:00Z'),
        endTime: new Date('2024-01-15T10:00:01Z'),
      }]

      const csv = generateCSVReport(tasksWithErrorQuotes)
      expect(csv).toContain('"Error: ""Something"" went wrong"')
    })

    it('includes duration in milliseconds', () => {
      const csv = generateCSVReport(mockTasks)
      expect(csv).toContain(',2000') // 2 seconds = 2000ms
    })

    it('handles tasks without times', () => {
      const pendingTasks: HydrationTask[] = [{
        id: 'pending-task',
        category: 'groups',
        operation: 'create',
        itemName: 'Pending Group',
        status: 'pending',
      }]

      const csv = generateCSVReport(pendingTasks)
      const lines = csv.split('\n')
      const dataLine = lines[1]

      // Should have empty values for time columns
      expect(dataLine).toMatch(/,,,\s*$/)
    })

    it('formats dates correctly', () => {
      const csv = generateCSVReport(mockTasks)
      // Check for date format pattern (timezone-agnostic)
      expect(csv).toMatch(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/)
    })
  })

  describe('createSummary', () => {
    it('calculates correct statistics for create mode', () => {
      const summary = createSummary(
        'tenant-123',
        'create',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:10:00Z'),
        mockTasks
      )

      expect(summary.stats.total).toBe(4)
      expect(summary.stats.created).toBe(2)
      expect(summary.stats.deleted).toBe(0)
      expect(summary.stats.skipped).toBe(1)
      expect(summary.stats.failed).toBe(1)
    })

    it('calculates correct statistics for delete mode', () => {
      const deleteTasks: HydrationTask[] = [
        { id: '1', category: 'groups', operation: 'delete', itemName: 'G1', status: 'success' },
        { id: '2', category: 'groups', operation: 'delete', itemName: 'G2', status: 'success' },
        { id: '3', category: 'filters', operation: 'delete', itemName: 'F1', status: 'failed', error: 'Not found' },
      ]

      const summary = createSummary(
        'tenant-123',
        'delete',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:05:00Z'),
        deleteTasks
      )

      expect(summary.stats.created).toBe(0)
      expect(summary.stats.deleted).toBe(2)
      expect(summary.stats.failed).toBe(1)
    })

    it('calculates duration correctly', () => {
      const startTime = new Date('2024-01-15T10:00:00Z')
      const endTime = new Date('2024-01-15T10:08:30Z')

      const summary = createSummary('tenant-123', 'create', startTime, endTime, mockTasks)

      expect(summary.duration).toBe(510000) // 8 minutes 30 seconds in ms
    })

    it('groups tasks by category correctly', () => {
      const summary = createSummary(
        'tenant-123',
        'create',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:10:00Z'),
        mockTasks
      )

      expect(summary.categoryBreakdown.groups.total).toBe(2)
      expect(summary.categoryBreakdown.groups.success).toBe(2)
      expect(summary.categoryBreakdown.filters.total).toBe(1)
      expect(summary.categoryBreakdown.filters.failed).toBe(1)
      expect(summary.categoryBreakdown.compliance.total).toBe(1)
      expect(summary.categoryBreakdown.compliance.skipped).toBe(1)
    })

    it('collects errors from failed tasks', () => {
      const summary = createSummary(
        'tenant-123',
        'create',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:10:00Z'),
        mockTasks
      )

      expect(summary.errors).toHaveLength(1)
      expect(summary.errors[0]).toMatchObject({
        task: 'Corporate Windows Devices',
        message: 'Insufficient permissions',
      })
    })

    it('handles empty task list', () => {
      const summary = createSummary(
        'tenant-123',
        'create',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:00:30Z'),
        []
      )

      expect(summary.stats.total).toBe(0)
      expect(summary.stats.created).toBe(0)
      expect(summary.stats.failed).toBe(0)
      expect(summary.categoryBreakdown).toEqual({})
      expect(summary.errors).toEqual([])
    })

    it('handles tasks without error message', () => {
      const failedNoError: HydrationTask[] = [{
        id: 'task-no-error',
        category: 'groups',
        operation: 'create',
        itemName: 'Failed Group',
        status: 'failed',
        endTime: new Date('2024-01-15T10:00:05Z'),
      }]

      const summary = createSummary(
        'tenant-123',
        'create',
        new Date('2024-01-15T10:00:00Z'),
        new Date('2024-01-15T10:01:00Z'),
        failedNoError
      )

      expect(summary.errors).toHaveLength(0) // No error because error field is undefined
    })
  })

  describe('generateReportFilename', () => {
    it('generates markdown filename with correct format', () => {
      const filename = generateReportFilename('create', 'md')
      expect(filename).toMatch(/^intune-hydration-create-\d{4}-\d{2}-\d{2}-\d{6}\.md$/)
    })

    it('generates JSON filename with correct format', () => {
      const filename = generateReportFilename('delete', 'json')
      expect(filename).toMatch(/^intune-hydration-delete-\d{4}-\d{2}-\d{2}-\d{6}\.json$/)
    })

    it('generates CSV filename with correct format', () => {
      const filename = generateReportFilename('preview', 'csv')
      expect(filename).toMatch(/^intune-hydration-preview-\d{4}-\d{2}-\d{2}-\d{6}\.csv$/)
    })
  })
})
