/**
 * Report generation for Intune Hydration Kit
 * Generates reports in Markdown, JSON, and CSV formats
 */

import { HydrationSummary, HydrationTask } from "@/types/hydration";
import { format } from "date-fns";

/**
 * Generate Markdown report
 */
export function generateMarkdownReport(
  summary: HydrationSummary,
  tasks: HydrationTask[]
): string {
  const duration = formatDuration(summary.duration);
  const timestamp = format(summary.startTime, "yyyy-MM-dd HH:mm:ss 'UTC'");

  let markdown = `# Intune Hydration Report

**Tenant ID**: ${summary.tenantId}
**Operation**: ${summary.operationMode.charAt(0).toUpperCase() + summary.operationMode.slice(1)}
**Date**: ${timestamp}
**Duration**: ${duration}

## Summary

- **Total Tasks**: ${summary.stats.total}
- **Created**: ${summary.stats.created}
- **Deleted**: ${summary.stats.deleted}
- **Skipped**: ${summary.stats.skipped}
- **Failed**: ${summary.stats.failed}

## Category Breakdown

`;

  // Add category breakdown
  for (const [category, stats] of Object.entries(summary.categoryBreakdown)) {
    const categoryName = formatCategoryName(category);
    markdown += `### ${categoryName} (${stats.total})\n`;
    markdown += `- Success: ${stats.success}\n`;
    markdown += `- Failed: ${stats.failed}\n\n`;
  }

  // Add task details
  markdown += `## Task Details\n\n`;

  const groupedTasks = groupTasksByCategory(tasks);

  for (const [category, categoryTasks] of Object.entries(groupedTasks)) {
    markdown += `### ${formatCategoryName(category)}\n\n`;

    for (const task of categoryTasks) {
      const icon = getTaskStatusIcon(task.status);
      markdown += `${icon} ${task.itemName}\n`;

      if (task.error) {
        markdown += `   - Error: ${task.error}\n`;
      }
      if (task.startTime && task.endTime) {
        const taskDuration = task.endTime.getTime() - task.startTime.getTime();
        markdown += `   - Duration: ${formatDuration(taskDuration)}\n`;
      }
    }

    markdown += `\n`;
  }

  // Add errors section if there are any
  if (summary.errors.length > 0) {
    markdown += `## Errors\n\n`;
    for (const error of summary.errors) {
      const errorTime = format(error.timestamp, "HH:mm:ss");
      markdown += `- **[${errorTime}]** ${error.task}: ${error.message}\n`;
    }
    markdown += `\n`;
  }

  // Add footer
  markdown += `---\n\n`;
  markdown += `*Generated by [Intune Hydration Kit](https://github.com/jorgeasaurus/IntuneHydrationKit)*\n`;

  return markdown;
}

/**
 * Generate JSON report
 */
export function generateJSONReport(
  summary: HydrationSummary,
  tasks: HydrationTask[]
): string {
  const report = {
    summary,
    tasks: tasks.map((task) => ({
      id: task.id,
      category: task.category,
      operation: task.operation,
      itemName: task.itemName,
      status: task.status,
      error: task.error,
      startTime: task.startTime?.toISOString(),
      endTime: task.endTime?.toISOString(),
      duration: task.startTime && task.endTime
        ? task.endTime.getTime() - task.startTime.getTime()
        : null,
    })),
    metadata: {
      reportVersion: "1.0",
      generatedAt: new Date().toISOString(),
    },
  };

  return JSON.stringify(report, null, 2);
}

/**
 * Generate CSV report
 */
export function generateCSVReport(tasks: HydrationTask[]): string {
  const headers = [
    "Category",
    "Item Name",
    "Operation",
    "Status",
    "Error",
    "Start Time",
    "End Time",
    "Duration (ms)",
  ];

  const rows = tasks.map((task) => {
    const duration =
      task.startTime && task.endTime
        ? task.endTime.getTime() - task.startTime.getTime()
        : "";

    return [
      task.category,
      `"${task.itemName.replace(/"/g, '""')}"`, // Escape quotes
      task.operation,
      task.status,
      task.error ? `"${task.error.replace(/"/g, '""')}"` : "",
      task.startTime ? format(task.startTime, "yyyy-MM-dd HH:mm:ss") : "",
      task.endTime ? format(task.endTime, "yyyy-MM-dd HH:mm:ss") : "",
      duration,
    ];
  });

  const csv = [headers, ...rows].map((row) => row.join(",")).join("\n");

  return csv;
}

/**
 * Create a hydration summary from execution results
 */
export function createSummary(
  tenantId: string,
  operationMode: "create" | "delete" | "preview",
  startTime: Date,
  endTime: Date,
  tasks: HydrationTask[]
): HydrationSummary {
  const stats = {
    total: tasks.length,
    created: tasks.filter((t) => t.status === "success" && operationMode === "create")
      .length,
    deleted: tasks.filter((t) => t.status === "success" && operationMode === "delete")
      .length,
    skipped: tasks.filter((t) => t.status === "skipped").length,
    failed: tasks.filter((t) => t.status === "failed").length,
  };

  // Group by category
  const categoryBreakdown: HydrationSummary["categoryBreakdown"] = {};
  for (const task of tasks) {
    if (!categoryBreakdown[task.category]) {
      categoryBreakdown[task.category] = {
        total: 0,
        success: 0,
        skipped: 0,
        failed: 0,
      };
    }

    categoryBreakdown[task.category].total++;
    if (task.status === "success") {
      categoryBreakdown[task.category].success++;
    } else if (task.status === "skipped") {
      categoryBreakdown[task.category].skipped++;
    } else if (task.status === "failed") {
      categoryBreakdown[task.category].failed++;
    }
  }

  // Collect errors
  const errors = tasks
    .filter((t) => t.status === "failed" && t.error)
    .map((t) => ({
      task: t.itemName,
      message: t.error || "Unknown error",
      timestamp: t.endTime || new Date(),
    }));

  return {
    tenantId,
    operationMode,
    startTime,
    endTime,
    duration: endTime.getTime() - startTime.getTime(),
    stats,
    categoryBreakdown,
    errors,
  };
}

/**
 * Download a report as a file
 */
export function downloadReport(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Format duration in milliseconds to human-readable string
 */
function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (hours > 0) {
    return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
  } else if (minutes > 0) {
    return `${minutes}m ${seconds % 60}s`;
  } else {
    return `${seconds}s`;
  }
}

/**
 * Get icon for task status
 */
function getTaskStatusIcon(status: string): string {
  switch (status) {
    case "success":
      return "✓";
    case "failed":
      return "✗";
    case "skipped":
      return "⊗";
    case "running":
      return "⏳";
    case "pending":
      return "○";
    default:
      return "-";
  }
}

/**
 * Format category name for display
 */
function formatCategoryName(category: string): string {
  const names: Record<string, string> = {
    groups: "Dynamic Groups",
    filters: "Device Filters",
    compliance: "Compliance Policies",
    conditionalAccess: "Conditional Access Policies",
    appProtection: "App Protection Policies",
    enrollment: "Enrollment Profiles",
    baseline: "OpenIntuneBaseline",
    notification: "Notification Templates",
  };

  return names[category] || category;
}

/**
 * Group tasks by category
 */
function groupTasksByCategory(
  tasks: HydrationTask[]
): Record<string, HydrationTask[]> {
  const grouped: Record<string, HydrationTask[]> = {};

  for (const task of tasks) {
    if (!grouped[task.category]) {
      grouped[task.category] = [];
    }
    grouped[task.category].push(task);
  }

  return grouped;
}

/**
 * Generate filename for report based on operation and timestamp
 */
export function generateReportFilename(
  operationMode: string,
  fileFormat: "md" | "json" | "csv"
): string {
  const timestamp = format(new Date(), "yyyy-MM-dd-HHmmss");
  return `intune-hydration-${operationMode}-${timestamp}.${fileFormat}`;
}
