/**
 * Report generation for Intune Hydration Kit
 * Generates reports in Markdown, JSON, and CSV formats
 */

import {
  HydrationSummary,
  HydrationTask,
  BatchExecutionStats,
  type ReportableExecutionOutcome,
} from "@/types/hydration";
import { formatClockTime, formatFileTimestamp } from "@/lib/utils/dateFormat";
import { getTaskEvidenceOutcome, type TaskEvidenceOutcome } from "@/lib/hydration/executionOutcome";
import { getTaskCategoryLabel } from "@/lib/hydration/categoryLabels";

const TASK_OUTCOME_LABELS: Record<TaskEvidenceOutcome, string> = {
  pending: "Pending",
  running: "Running",
  success: "Success",
  failed: "Failed",
  noOp: "No change",
  blocked: "Blocked",
  cancelled: "Cancelled",
};

const RUN_OUTCOME_LABELS: Record<ReportableExecutionOutcome, string> = {
  succeeded: "Succeeded",
  completedWithIssues: "Completed with issues",
  cancelled: "Cancelled",
};

function formatUtcDateTime(date: Date): string {
  return date.toISOString().replace("T", " ").slice(0, 19);
}

/**
 * Generate Markdown report
 */
export function generateMarkdownReport(
  summary: HydrationSummary,
  tasks: HydrationTask[],
  outcome: ReportableExecutionOutcome,
): string {
  const duration = formatDuration(summary.duration);
  // Render actual UTC time (toISOString), not local time with a hardcoded UTC label
  const timestamp = `${formatUtcDateTime(summary.startTime)} UTC`;

  let markdown = `# Intune Hydration Report

**Tenant ID**: ${summary.tenantId}
**Operation**: ${summary.operationMode.charAt(0).toUpperCase() + summary.operationMode.slice(1)}
**Outcome**: ${RUN_OUTCOME_LABELS[outcome]}
**Date**: ${timestamp}
**Duration**: ${duration}

## Summary

- **Total Tasks**: ${summary.stats.total}
- **Created**: ${summary.stats.created}
- **Deleted**: ${summary.stats.deleted}
- **Skipped**: ${summary.stats.skipped}
- **Failed**: ${summary.stats.failed}${
    summary.batchStats
      ? `

### Batch Execution
- **Batch Size**: ${summary.batchStats.batchSize}
- **Batch Requests**: ${summary.batchStats.batchRequestCount}
- **Batched Tasks**: ${summary.batchStats.batchedTaskCount}
- **Sequential Tasks**: ${summary.batchStats.sequentialTaskCount}`
      : ""
  }

## Category Breakdown

`;

  // Add category breakdown
  for (const [category, stats] of Object.entries(summary.categoryBreakdown)) {
    const categoryName = getTaskCategoryLabel(category);
    markdown += `### ${categoryName} (${stats.total})\n`;
    markdown += `- Success: ${stats.success}\n`;
    markdown += `- Failed: ${stats.failed}\n\n`;
  }

  // Add task details
  markdown += `## Task Details\n\n`;

  const groupedTasks = groupTasksByCategory(tasks);

  for (const [category, categoryTasks] of Object.entries(groupedTasks)) {
    markdown += `### ${getTaskCategoryLabel(category)}\n\n`;

    for (const task of categoryTasks) {
      const icon = getTaskStatusIcon(task.status);
      markdown += `${icon} ${task.itemName}\n`;
      markdown += `   - Outcome: ${TASK_OUTCOME_LABELS[getTaskEvidenceOutcome(task)]}\n`;

      if (task.error) {
        markdown += `   - Error: ${task.error}\n`;
      }
      if (task.warning) {
        markdown += `   - Warning: ${task.warning}\n`;
      }
      if (task.startTime && task.endTime) {
        const taskDuration = task.endTime.getTime() - task.startTime.getTime();
        markdown += `   - Duration: ${formatDuration(taskDuration)}\n`;
      }
    }

    markdown += `\n`;
  }

  // Add warnings section if there are any
  if (summary.warnings.length > 0) {
    markdown += `## Warnings\n\n`;
    markdown += `The following policies were created but require manual configuration:\n\n`;
    for (const warning of summary.warnings) {
      const warningTime = formatClockTime(warning.timestamp);
      markdown += `- **[${warningTime}]** ${warning.task}: ${warning.message}\n`;
    }
    markdown += `\n`;
  }

  // Add errors section if there are any
  if (summary.errors.length > 0) {
    markdown += `## Errors\n\n`;
    for (const error of summary.errors) {
      const errorTime = formatClockTime(error.timestamp);
      markdown += `- **[${errorTime}]** ${error.task}: ${error.message}\n`;
    }
    markdown += `\n`;
  }

  // Add footer
  markdown += `---\n\n`;
  markdown += `*Generated by [Intune Hydration Kit](https://github.com/jorgeasaurus/IntuneHydrationKit-WebApp)*\n`;

  return markdown;
}

/**
 * Generate JSON report
 */
export function generateJSONReport(
  summary: HydrationSummary,
  tasks: HydrationTask[],
  outcome: ReportableExecutionOutcome,
): string {
  const report = {
    outcome,
    summary,
    tasks: tasks.map((task) => ({
      id: task.id,
      category: task.category,
      operation: task.operation,
      itemName: task.itemName,
      status: task.status,
      outcome: getTaskEvidenceOutcome(task),
      error: task.error,
      warning: task.warning,
      startTime: task.startTime?.toISOString(),
      endTime: task.endTime?.toISOString(),
      duration: task.startTime && task.endTime ? task.endTime.getTime() - task.startTime.getTime() : null,
    })),
    metadata: {
      reportVersion: "1.0",
      generatedAt: new Date().toISOString(),
    },
  };

  return JSON.stringify(report, null, 2);
}

/**
 * Generate CSV report
 */
export function generateCSVReport(tasks: HydrationTask[], outcome: ReportableExecutionOutcome): string {
  const headers = [
    "Category",
    "Item Name",
    "Operation",
    "Run Outcome",
    "Status",
    "Outcome",
    "Error",
    "Warning",
    "Start Time (UTC)",
    "End Time (UTC)",
    "Duration (ms)",
  ];

  // Quote-escape every field so commas/quotes/newlines in any value can't break the CSV.
  // Values starting with =, +, -, @ (or tab/CR) are prefixed with ' to neutralize
  // spreadsheet formula injection (a policy named "=cmd|..." must not execute in Excel).
  // Leading whitespace is checked too - Excel trims it before evaluating formulas.
  const escapeCSVField = (value: string | number): string => {
    let str = String(value);
    if (/^\s*[=+\-@\t\r]/.test(str)) {
      str = `'${str}`;
    }
    return `"${str.replace(/"/g, '""')}"`;
  };

  const rows = tasks.map((task) => {
    const duration = task.startTime && task.endTime ? task.endTime.getTime() - task.startTime.getTime() : "";

    return [
      task.category,
      task.itemName,
      task.operation,
      outcome,
      task.status,
      getTaskEvidenceOutcome(task),
      task.error ?? "",
      task.warning ?? "",
      task.startTime ? formatUtcDateTime(task.startTime) : "",
      task.endTime ? formatUtcDateTime(task.endTime) : "",
      duration,
    ].map(escapeCSVField);
  });

  if (rows.length === 0) {
    rows.push(["", "", "", outcome, "", "", "", "", "", "", ""].map(escapeCSVField));
  }

  const csv = [headers.map(escapeCSVField), ...rows].map((row) => row.join(",")).join("\n");

  return csv;
}

/**
 * Create a hydration summary from execution results
 */
export function createSummary(
  tenantId: string,
  operationMode: "create" | "delete",
  startTime: Date,
  endTime: Date,
  tasks: HydrationTask[],
  batchStats?: BatchExecutionStats,
  tenantName?: string,
): HydrationSummary {
  const stats = {
    total: tasks.length,
    created: tasks.filter((t) => t.status === "success" && t.operation === "create").length,
    deleted: tasks.filter((t) => t.status === "success" && t.operation === "delete").length,
    skipped: tasks.filter((t) => t.status === "skipped").length,
    failed: tasks.filter((t) => t.status === "failed").length,
  };

  // Group by category
  const categoryBreakdown: HydrationSummary["categoryBreakdown"] = {};
  for (const task of tasks) {
    if (!categoryBreakdown[task.category]) {
      categoryBreakdown[task.category] = {
        total: 0,
        success: 0,
        skipped: 0,
        failed: 0,
      };
    }

    categoryBreakdown[task.category].total++;
    if (task.status === "success") {
      categoryBreakdown[task.category].success++;
    } else if (task.status === "skipped") {
      categoryBreakdown[task.category].skipped++;
    } else if (task.status === "failed") {
      categoryBreakdown[task.category].failed++;
    }
  }

  // Collect errors
  const errors = tasks.reduce<HydrationSummary["errors"]>((items, task) => {
    if (task.status === "failed" && task.error) {
      items.push({
        task: task.itemName,
        message: task.error || "Unknown error",
        timestamp: task.endTime || endTime,
      });
    }
    return items;
  }, []);

  // Collect warnings (tasks that succeeded but have warnings)
  const warnings = tasks.reduce<HydrationSummary["warnings"]>((items, task) => {
    if (task.status === "success" && task.warning) {
      items.push({
        task: task.itemName,
        message: task.warning || "",
        timestamp: task.endTime || endTime,
      });
    }
    return items;
  }, []);

  return {
    tenantId,
    tenantName,
    operationMode,
    startTime,
    endTime,
    duration: endTime.getTime() - startTime.getTime(),
    stats,
    categoryBreakdown,
    errors,
    warnings,
    batchStats,
  };
}

export function summaryMatchesExecution(
  summary: HydrationSummary,
  source: Pick<HydrationSummary, "tenantId" | "tenantName" | "operationMode" | "startTime" | "endTime"> & {
    tasks: HydrationTask[];
  },
): boolean {
  const expected = createSummary(
    source.tenantId,
    source.operationMode,
    source.startTime,
    source.endTime,
    source.tasks,
    summary.batchStats,
    source.tenantName,
  );
  return JSON.stringify(toCanonicalValue(summary)) === JSON.stringify(toCanonicalValue(expected));
}

function toCanonicalValue(value: unknown): unknown {
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(toCanonicalValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, toCanonicalValue(item)]),
    );
  }
  return value;
}

/**
 * Download a report as a file
 */
export function downloadReport(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Format duration in milliseconds to human-readable string
 */
function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (hours > 0) {
    return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
  } else if (minutes > 0) {
    return `${minutes}m ${seconds % 60}s`;
  } else {
    return `${seconds}s`;
  }
}

/**
 * Get icon for task status
 */
function getTaskStatusIcon(status: string): string {
  switch (status) {
    case "success":
      return "✓";
    case "failed":
      return "✗";
    case "skipped":
      return "⊗";
    case "running":
      return "⏳";
    case "pending":
      return "○";
    default:
      return "-";
  }
}

/**
 * Group tasks by category
 */
function groupTasksByCategory(tasks: HydrationTask[]): Record<string, HydrationTask[]> {
  return tasks.reduce<Record<string, HydrationTask[]>>((grouped, task) => {
    (grouped[task.category] ??= []).push(task);
    return grouped;
  }, {});
}

/**
 * Generate filename for report based on operation and timestamp
 */
export function generateReportFilename(operationMode: string, fileFormat: "md" | "json" | "csv"): string {
  const timestamp = formatFileTimestamp(new Date());
  return `intune-hydration-${operationMode}-${timestamp}.${fileFormat}`;
}
