/**
 * Compliance Policy Templates for Intune Hydration Kit
 * Based on security best practices and baselines
 */

import { CompliancePolicy } from "@/types/graph";

const HYDRATION_MARKER = "Imported by Intune-Hydration-Kit";

export const COMPLIANCE_POLICIES: CompliancePolicy[] = [
  {
    "@odata.type": "#microsoft.graph.windows10CompliancePolicy",
    displayName: "Windows 10 - Security Baseline",
    description: `Windows 10 compliance policy enforcing security baseline requirements. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordRequiredType: "alphanumeric",
    passwordMinimumLength: 14,
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordExpirationDays: 0,
    passwordPreviousPasswordBlockCount: 24,
    requireHealthyDeviceReport: true,
    osMinimumVersion: "10.0.19041.0",
    osMaximumVersion: null,
    earlyLaunchAntiMalwareDriverEnabled: true,
    bitLockerEnabled: true,
    secureBootEnabled: true,
    codeIntegrityEnabled: true,
    storageRequireEncryption: true,
    activeFirewallRequired: true,
    defenderEnabled: true,
    defenderVersion: null,
    signatureOutOfDate: false,
    rtpEnabled: true,
    antivirusRequired: true,
    antiSpywareRequired: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "medium",
    configurationManagerComplianceRequired: false,
    tpmRequired: true,
    deviceCompliancePolicyScript: null,
    validOperatingSystemBuildRanges: [],
  },
  {
    "@odata.type": "#microsoft.graph.windows10CompliancePolicy",
    displayName: "Windows 11 - Security Baseline",
    description: `Windows 11 compliance policy enforcing security baseline requirements. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordRequiredType: "alphanumeric",
    passwordMinimumLength: 14,
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordExpirationDays: 0,
    passwordPreviousPasswordBlockCount: 24,
    requireHealthyDeviceReport: true,
    osMinimumVersion: "10.0.22000.0",
    osMaximumVersion: null,
    earlyLaunchAntiMalwareDriverEnabled: true,
    bitLockerEnabled: true,
    secureBootEnabled: true,
    codeIntegrityEnabled: true,
    storageRequireEncryption: true,
    activeFirewallRequired: true,
    defenderEnabled: true,
    defenderVersion: null,
    signatureOutOfDate: false,
    rtpEnabled: true,
    antivirusRequired: true,
    antiSpywareRequired: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "medium",
    configurationManagerComplianceRequired: false,
    tpmRequired: true,
    deviceCompliancePolicyScript: null,
    validOperatingSystemBuildRanges: [],
  },
  {
    "@odata.type": "#microsoft.graph.iosCompliancePolicy",
    displayName: "iOS - Security Baseline",
    description: `iOS compliance policy enforcing security baseline requirements. ${HYDRATION_MARKER}`,
    passcodeBlockSimple: true,
    passcodeExpirationDays: 0,
    passcodeMinimumLength: 6,
    passcodeMinutesOfInactivityBeforeLock: 15,
    passcodeMinimumCharacterSetCount: 3,
    passcodePreviousPasscodeBlockCount: 24,
    passcodeRequired: true,
    passcodeRequiredType: "alphanumeric",
    osMinimumVersion: "15.0",
    osMaximumVersion: null,
    osMinimumBuildVersion: null,
    osMaximumBuildVersion: null,
    securityBlockJailbrokenDevices: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "medium",
    managedEmailProfileRequired: false,
    restrictedApps: [],
  },
  {
    "@odata.type": "#microsoft.graph.androidCompliancePolicy",
    displayName: "Android - Security Baseline",
    description: `Android compliance policy enforcing security baseline requirements. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordMinimumLength: 6,
    passwordRequiredType: "alphanumeric",
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordExpirationDays: 0,
    passwordPreviousPasswordBlockCount: 24,
    storageRequireEncryption: true,
    securityPreventInstallAppsFromUnknownSources: true,
    securityDisableUsbDebugging: true,
    securityRequireVerifyApps: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "medium",
    securityBlockJailbrokenDevices: true,
    osMinimumVersion: "10.0",
    osMaximumVersion: null,
    minAndroidSecurityPatchLevel: null,
    restrictedApps: [],
  },
  {
    "@odata.type": "#microsoft.graph.macOSCompliancePolicy",
    displayName: "macOS - Security Baseline",
    description: `macOS compliance policy enforcing security baseline requirements. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordExpirationDays: 0,
    passwordMinimumLength: 14,
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordPreviousPasswordBlockCount: 24,
    passwordMinimumCharacterSetCount: 3,
    passwordRequiredType: "alphanumeric",
    osMinimumVersion: "12.0",
    osMaximumVersion: null,
    osMinimumBuildVersion: null,
    osMaximumBuildVersion: null,
    systemIntegrityProtectionEnabled: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "medium",
    storageRequireEncryption: true,
    gatekeeperAllowedAppSource: "macAppStoreAndIdentifiedDevelopers",
    firewallEnabled: true,
    firewallBlockAllIncoming: false,
    firewallEnableStealthMode: true,
  },
  {
    "@odata.type": "#microsoft.graph.windows10CompliancePolicy",
    displayName: "Windows - BYOD Basic",
    description: `Basic Windows compliance policy for personal (BYOD) devices. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordRequiredType: "alphanumeric",
    passwordMinimumLength: 8,
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordExpirationDays: 0,
    passwordPreviousPasswordBlockCount: 5,
    requireHealthyDeviceReport: false,
    osMinimumVersion: "10.0.19041.0",
    osMaximumVersion: null,
    bitLockerEnabled: false,
    secureBootEnabled: false,
    codeIntegrityEnabled: false,
    storageRequireEncryption: true,
    activeFirewallRequired: true,
    defenderEnabled: true,
    rtpEnabled: true,
    antivirusRequired: true,
    antiSpywareRequired: true,
    deviceThreatProtectionEnabled: false,
    deviceThreatProtectionRequiredSecurityLevel: "unavailable",
    tpmRequired: false,
  },
  {
    "@odata.type": "#microsoft.graph.iosCompliancePolicy",
    displayName: "iOS - BYOD Basic",
    description: `Basic iOS compliance policy for personal (BYOD) devices. ${HYDRATION_MARKER}`,
    passcodeBlockSimple: true,
    passcodeExpirationDays: 0,
    passcodeMinimumLength: 6,
    passcodeMinutesOfInactivityBeforeLock: 15,
    passcodeMinimumCharacterSetCount: 2,
    passcodePreviousPasscodeBlockCount: 5,
    passcodeRequired: true,
    passcodeRequiredType: "numeric",
    osMinimumVersion: "14.0",
    osMaximumVersion: null,
    securityBlockJailbrokenDevices: true,
    deviceThreatProtectionEnabled: false,
    deviceThreatProtectionRequiredSecurityLevel: "unavailable",
    managedEmailProfileRequired: false,
  },
  {
    "@odata.type": "#microsoft.graph.androidCompliancePolicy",
    displayName: "Android - BYOD Basic",
    description: `Basic Android compliance policy for personal (BYOD) devices. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordMinimumLength: 6,
    passwordRequiredType: "numeric",
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordExpirationDays: 0,
    passwordPreviousPasswordBlockCount: 5,
    storageRequireEncryption: true,
    securityPreventInstallAppsFromUnknownSources: true,
    securityDisableUsbDebugging: false,
    securityRequireVerifyApps: true,
    deviceThreatProtectionEnabled: false,
    deviceThreatProtectionRequiredSecurityLevel: "unavailable",
    securityBlockJailbrokenDevices: true,
    osMinimumVersion: "9.0",
    osMaximumVersion: null,
  },
  {
    "@odata.type": "#microsoft.graph.macOSCompliancePolicy",
    displayName: "macOS - BYOD Basic",
    description: `Basic macOS compliance policy for personal (BYOD) devices. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordExpirationDays: 0,
    passwordMinimumLength: 8,
    passwordMinutesOfInactivityBeforeLock: 15,
    passwordPreviousPasswordBlockCount: 5,
    passwordMinimumCharacterSetCount: 2,
    passwordRequiredType: "alphanumeric",
    osMinimumVersion: "11.0",
    osMaximumVersion: null,
    systemIntegrityProtectionEnabled: true,
    deviceThreatProtectionEnabled: false,
    deviceThreatProtectionRequiredSecurityLevel: "unavailable",
    storageRequireEncryption: true,
    firewallEnabled: true,
  },
  {
    "@odata.type": "#microsoft.graph.windows10CompliancePolicy",
    displayName: "Windows - Highly Secured Devices",
    description: `Highly secure Windows compliance policy for sensitive environments. ${HYDRATION_MARKER}`,
    passwordRequired: true,
    passwordBlockSimple: true,
    passwordRequiredType: "alphanumeric",
    passwordMinimumLength: 16,
    passwordMinutesOfInactivityBeforeLock: 5,
    passwordExpirationDays: 90,
    passwordPreviousPasswordBlockCount: 24,
    requireHealthyDeviceReport: true,
    osMinimumVersion: "10.0.22000.0",
    osMaximumVersion: null,
    earlyLaunchAntiMalwareDriverEnabled: true,
    bitLockerEnabled: true,
    secureBootEnabled: true,
    codeIntegrityEnabled: true,
    storageRequireEncryption: true,
    activeFirewallRequired: true,
    defenderEnabled: true,
    signatureOutOfDate: false,
    rtpEnabled: true,
    antivirusRequired: true,
    antiSpywareRequired: true,
    deviceThreatProtectionEnabled: true,
    deviceThreatProtectionRequiredSecurityLevel: "secured",
    configurationManagerComplianceRequired: false,
    tpmRequired: true,
  },
];

/**
 * Get all compliance policy templates
 */
export function getCompliancePolicies(): CompliancePolicy[] {
  return COMPLIANCE_POLICIES;
}

/**
 * Get compliance policies for a specific platform
 */
export function getCompliancePoliciesByPlatform(platform: string): CompliancePolicy[] {
  const platformMap: Record<string, string> = {
    windows: "#microsoft.graph.windows10CompliancePolicy",
    ios: "#microsoft.graph.iosCompliancePolicy",
    android: "#microsoft.graph.androidCompliancePolicy",
    macos: "#microsoft.graph.macOSCompliancePolicy",
  };

  const odataType = platformMap[platform.toLowerCase()];
  if (!odataType) {
    return [];
  }

  return COMPLIANCE_POLICIES.filter((policy) => policy["@odata.type"] === odataType);
}

/**
 * Get a specific compliance policy by display name
 */
export function getCompliancePolicyByName(
  displayName: string
): CompliancePolicy | undefined {
  return COMPLIANCE_POLICIES.find(
    (policy) => policy.displayName.toLowerCase() === displayName.toLowerCase()
  );
}
