/**
 * Central export for all Intune Hydration Kit templates
 */

export * from "./groups";
export * from "./filters";
export * from "./compliance";
export * from "./conditionalAccess";
export * from "./appProtection";
export * from "./enrollment";

/**
 * Template metadata for UI display
 * Counts match the source PowerShell project: https://github.com/jorgeasaurus/IntuneHydrationKit
 */
export const TEMPLATE_METADATA = {
  groups: {
    displayName: "Entra Groups",
    description: "Dynamic and static groups for device/user categorization (50 dynamic + 5 static)",
    count: 55,
    icon: "Users",
  },
  filters: {
    displayName: "Device Filters",
    description: "Assignment filters for granular policy targeting",
    count: 24,
    icon: "Filter",
  },
  baseline: {
    displayName: "OpenIntuneBaseline",
    description: "Security baseline policies (Windows, macOS)",
    count: 93,
    icon: "ShieldCheck",
  },
  compliance: {
    displayName: "Compliance Policies",
    description: "Device compliance policies for Windows, Apple, Android, and Linux",
    count: 10,
    icon: "Shield",
  },
  appProtection: {
    displayName: "App Protection",
    description: "Mobile application management (MAM) policies",
    count: 8,
    icon: "Smartphone",
  },
  enrollment: {
    displayName: "Enrollment Profiles",
    description: "Windows Autopilot, ESP, and Device Preparation profiles",
    count: 4,
    icon: "Download",
  },
  conditionalAccess: {
    displayName: "Conditional Access",
    description: "Microsoft starter pack CA policies (created in disabled state)",
    count: 21,
    icon: "Lock",
  },
  cisBaseline: {
    displayName: "CIS Intune Baselines",
    description: "CIS security benchmarks for Windows, macOS, iOS, Android, and browsers",
    count: 717,
    icon: "ShieldAlert",
    hasSubcategories: true,
  },
} as const;

/**
 * CIS Baseline category metadata (static fallback)
 * This matches the category IDs generated by scripts/generate-cis-manifest.js
 */
export const CIS_CATEGORY_METADATA = {
  "cis-android": {
    id: "cis-android",
    name: "Android Benchmarks",
    description: "Android Enterprise and compliance policies",
    count: 17,
  },
  "cis-apple": {
    id: "cis-apple",
    name: "Apple Benchmarks",
    description: "macOS and iOS security configurations",
    count: 40,
  },
  "cis-browser": {
    id: "cis-browser",
    name: "Browser Benchmarks",
    description: "Chrome and Edge browser security settings",
    count: 17,
  },
  "cis-windows-cis": {
    id: "cis-windows-cis",
    name: "CIS Windows 11 Benchmarks",
    description: "CIS security benchmarks for Windows 11 and macOS",
    count: 501,
  },
  "cis-linux": {
    id: "cis-linux",
    name: "Linux Benchmarks",
    description: "Linux compliance policies",
    count: 1,
  },
  "cis-endpoint-security": {
    id: "cis-endpoint-security",
    name: "Microsoft Endpoint Security",
    description: "Endpoint Security antivirus and firewall policies",
    count: 57,
  },
  "cis-visual-studio": {
    id: "cis-visual-studio",
    name: "Visual Studio Benchmarks",
    description: "Visual Studio and VS Code security settings",
    count: 8,
  },
  "cis-windows-11": {
    id: "cis-windows-11",
    name: "Windows 11 Benchmarks",
    description: "Windows 11 BitLocker, Edge, and M365 Apps settings",
    count: 56,
  },
  "cis-cloud-pc": {
    id: "cis-cloud-pc",
    name: "Windows Cloud PC & AVD",
    description: "Azure Virtual Desktop and Windows 365 policies",
    count: 20,
  },
} as const;

/**
 * Get total count of all templates
 */
export function getTotalTemplateCount(): number {
  return Object.values(TEMPLATE_METADATA).reduce((sum, meta) => sum + meta.count, 0);
}
